### ISSUE TITLE
Setting up new whitelist creator

### ISSUE THREAD

**Issue by ronhillgaming** [qbcore-framework/qb-lapraces#18]
What name is necessary to give a player access to race creation? I see the line in config.lua and have added a player to the list using his steam name but it is not working for us. He still get the message he does not have permission to create a track. Here is what I've done:
Config = Config or {}

Config.WhitelistedCreators = {
    "PUTCID",
    "StreetRacer1748",
}

Config.RaceSetupAllowed = true

The player "StreetRacer1748" is who I am trying to add to the list. I can make tracks as an admin but we do not want to give admin perms just for racing. Thanks.

**Comment by ronhillgaming** [comment]
I figured it out to PUT Citizen ID in that line. Sorry to bother you.

**Comment by L1quidSn4ke** [comment]
Please close this if its resolved

**Comment by ronhillgaming** [comment]
It works perfectly now.

**Comment by yRocxs** [comment]
Could you show how your code looks, I'm having problems with mine. @ronhillgaming
