### ISSUE TITLE
end of race leaderboard/payout

### ISSUE THREAD

**Issue by Djpowell23** [qbcore-framework/qb-lapraces#20]
Hello. I've been trying this for a while but I'm trying to get it so when there are more than 5 people who start a race, police can be alerted, and also when there are more than 5 in a race, there is a payout for 1st, 2nd, and 3rd. I got close but every time people finished the race, it thought each person was coming in first since they left the race upon completion. Are you able to help or implement something where that is configurable?

**Comment by IdrisDose** [comment]
Hey, This particular resource has been discarded for a bit, I've recently been assigned for this month so I'll go over it in my freetime and get back to you, sorry about the delay.

**Comment by w4fflz** [comment]
qb-streetraces offers payouts.  Maybe try that or are you wanting lap races to do it also?
