### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Revline-RP** [qbcore-framework/qb-lapraces#33]
Hi there!

Keep getting `qb-lapraces/server/main.lua:238: attempt to index a nil value (field '?')` when we attempt to join a created race!

Any idea what might be causing this?

**Comment by Revline-RP** [comment]
Worth to mention we set it up using qb-phone!

**Comment by SulakAlNanna** [comment]
> Worth to mention we set it up using qb-phone!

It stores the data separately from the phone if you use the phone but changed the .sql file for lapraces then that will cause the issue. If you want to use both you need to keep both tables in the db

**Comment by porkandbeans** [comment]
this may be an issue with qb-phone/html/js/racing.js, I have submitted a PR to fix it

**Comment by alfiswielki** [comment]
> może to być problem z qb-phone/html/js/racing.js, przesłałem PR, aby to naprawić

what rr? was it possible to repair? Where can I find a way to fix it?

**Comment by AbelMel** [comment]
Hi, go to your "QB-Phone" open the "html" folder and the open the "racing.js" file, after you are in the "racing.js" replace the entire code with this code.
[racing.txt](https://github.com/qbcore-framework/qb-lapraces/files/10138065/racing.txt)

**Comment by Janidu-24** [comment]
replace the entire code with this code.
[racing.txt](https://github.com/qbcore-framework/qb-lapraces/files/11524145/racing.txt)
