### ISSUE TITLE
Players can have different timers than each other

### ISSUE THREAD

**Issue by Masi42** [qbcore-framework/qb-lapraces#4]
Players can have different timers than each other. I believe Ping effects the racing timer which leaves players with Higher Ping getting much quicker results than other players who finish the race at the same time.

**Comment by am3nd01m** [comment]
I've experienced this issue too.

**Comment by maguhd** [comment]
+

**Comment by maguhd** [comment]
> I've experienced this issue too.

Me too

**Comment by bruinp8n** [comment]
Me 3
