### ISSUE TITLE
I can't create a track

### ISSUE THREAD

**Issue by truong724627** [qbcore-framework/qb-lapraces#43]
![Ảnh chụp màn hình (15)](https://github.com/qbcore-framework/qb-lapraces/assets/133361794/6e673ac9-2382-44d2-ada5-796b58808bd7)
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by truong724627** [comment]
help me

**Comment by Skuteriss** [comment]
still the same....

**Comment by WizardOfOzcar** [comment]
Have you added the ID of the person who can create races into the Config.lua?

It has be be the **"CIV ID"** that you find when using the citizen card
![image_2023-08-26_124242759](https://github.com/qbcore-framework/qb-lapraces/assets/141676435/352e437b-64e0-4bb2-908f-7bf7b20f5f4b)

![20230826123906_1](https://github.com/qbcore-framework/qb-lapraces/assets/141676435/49798554-a546-421c-b54b-4e759d615789)

**Comment by 39278899Mm** [comment]
Tnx for the i did not know what id to add there lol
